#! /usr/bin/python

import sys
import ldap
from ldapConf import *
from optparse import OptionParser

from ldapConf import *
from ldapUtil import *


####################################################################################
# global constants
####################################################################################
version="%prog: v0.82 (2011-Nov-27)"
modifiedBy="Garry Thuna"


###################################################################################
# parse command line options
###################################################################################
usage = "usage: %prog [options] [hostUri] [bindDN] [bindPW]" 
description = "Create a user in " + BASE_DN
parser = OptionParser(usage=usage, version=version, description=description)
parser.add_option("-H", action="store", type="string", dest="hostUri",
                        help="LDAP Uniform Resource Identifier (eg. ldaps://ldapServer:port)")
parser.add_option("-D", action="store", type="string", dest="bindDN", help="bind DN")
parser.add_option("-w", action="store", type="string", dest="bindPass", help="bind password")
(options, args) = parser.parse_args()

####################################################################################
# gather the user input
####################################################################################
if options.hostUri:
    hostUri = options.hostUri
elif len(args) >= 1:
    hostUri = args[0]
else: 
    hostUri = "ldaps://example.com:636"
input = raw_input('host URI [{0}]: '.format(hostUri)).strip()
if len(input) != 0:
    hostUri = input

if options.bindDN:
    bindDN = options.bindDN
elif len(args) >= 2:
    bindDN = args[1]
else: 
    bindDN = ""
input = raw_input('bind DN [{0}]: '.format(bindDN)).strip()
if len(input) != 0:
    bindDN = input

if options.bindPass:
    bindPass = options.bindPass
elif len(args) >= 3:
    bindPass = args[2]
else: 
    bindPass = raw_input('bind password: ')

gid = raw_input('group ID: ')
displayName = raw_input('display name: ')
description = raw_input('description: ')


####################################################################################
# bind to the ldap server
#     do the preliminary procssing of users and groups
#     do the preliminary procssing of workspaces
####################################################################################
con = ldap.initialize(hostUri)
con.start_tls_s()
con.simple_bind_s(bindDN, bindPass)

groups,                \
    users,             \
     gnum2idx,         \
     gid2idx,          \
     uid2idx,          \
     belongsTo,        \
    workspaces,        \
     awsName2ws,       \
     awsName2path,     \
     gnum2awsName,     \
    servers,           \
     asName2server  = preProcessLdapObjects(con)

# calc the maximum gidNumber
maxGidNumber = 0 
for g in groups:
    cur = int(g[1]['gidNumber'][0])
    if cur > maxGidNumber:
        maxGidNumber = cur
gidNumber = maxGidNumber + 1

# setup the entry's attributes
dn = GROUP_DN_FMT.format(gid)
ur = list()
ur.append( ('objectClass', ['sambaGroupMapping', 'posixGroup']) )
ur.append( ('cn',                   [gid])                                                      )  
ur.append( ('gidNumber',            ['{0}'.format(gidNumber)])                                  )  
ur.append( ('sambaGroupType',       ['2'])                                                      )  
ur.append( ('sambaSID',             ['S-1-5-21-12345-1-{0}'.format(gidNumber * 2 + 1)])         ) 
ur.append( ('displayName',          [displayName])                                              )
ur.append( ('description',          [description])                                              )

con.add_s(dn, ur)
con.unbind_s()


